'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header/page.js";
import { DataProvider } from './Context/PopupContext.js';
import StyledComponentsRegistry from './lib/AntdRegistry';
import { AuthProvider } from "./Context/AuthContext";
import { ConfigProvider } from 'antd';
import { Provider } from 'react-redux';
import { store } from './redux/store.js';

const config = {
  "token": {
    "colorPrimary": "#52c41a",
    "colorInfo": "#52c41a"
  },
  "components": {
    "Menu": {
      "itemSelectedBg": "rgb(22, 119, 255)",
      "colorText": "rgb(245, 34, 45)"
    }
  }
}

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <StyledComponentsRegistry>
            <div className="main-layout">
              <ConfigProvider theme={config}>
                <DataProvider>
                  <AuthProvider>
                    <Header />
                    {children}
                  </AuthProvider>
                </DataProvider>
              </ConfigProvider>
            </div>
          </StyledComponentsRegistry>
        </Provider>
      </body>
    </html>
  );
}
